
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_POSTS_INIT = 'FETCH_POSTS_INIT';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCH_POST_INIT = 'FETCH_POST_INIT';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const ADD_FAV_INIT = 'ADD_FAV_INIT';
export const ADD_FAV_SUCCESS = 'ADD_FAV_SUCCESS';
export const ADD_FAV_FAILED = 'ADD_FAV_FAILED';

export const REMOVE_FAV_INIT = 'REMOVE_FAV_INIT';
export const REMOVE_FAV_SUCCESS = 'REMOVE_FAV_SUCCESS';
export const REMOVE_FAV_FAILED = 'REMOVE_FAV_FAILED';

export const EDIT_PROFILE_INIT = 'EDIT_PROFILE_INIT';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';